# Generated by Django 4.2.5 on 2023-11-15 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menusapp', '0003_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='codigo_autorizacion',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='token_transbank',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='boleta',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
